### ISSUE TITLE
关于睡眠功能

### ISSUE THREAD

**Issue by Speed4fly** [Fansaly/xiaoHei-Practice#2]
老哥你好，你的配置可以成功睡眠吗～
我自己弄的10.10.4系统没办法睡眠愁死了，不知道咋整～

**Comment by Fansaly** [comment]
系统 10.14.4，睡眠、唤醒都正常，我的是 小新 v2000。
建议安装最新版本系统，因为不同版本 patch 是不同的。

参照 [hotpatch](https://github.com/Fansaly/xiaoHei-Practice/blob/master/patch_hotpatch.md)，除 `config.plist` 可能需要需改之外，其他不需要修改。

**Comment by Speed4fly** [comment]
谢谢你朋友！不过好像hotpatch有点bug，我连续两次安装时死机，efi分区就凉了（然后重装了好多次）……不过从U盘启动硬盘系统再次安装侥幸没有死机，现在我的也基本完美啦~
